export const countryData = {
  bank: {
    Syria: ['BIMO', 'International Islamic Bank of Syria'],
    UAE: ['Emirates NBD', 'Abu Dhabi Commercial Bank', 'Dubai Islamic Bank'],
    Egypt: ['National Bank of Egypt', 'Commercial International Bank', 'Banque Misr'],
    Saudi: ['Al Rajhi Bank', 'Saudi National Bank', 'Riyad Bank'],
    Turkey: ['Ziraat Bank', 'İş Bank', 'Garanti BBVA'],
    Lebanon: ['Bank Audi', 'BLOM Bank', 'Byblos Bank'],
    Jordan: ['Arab Bank', 'Housing Bank', 'Jordan Islamic Bank'],
    Iraq: ['Trade Bank of Iraq', 'National Bank of Iraq'],
    Kuwait: ['National Bank of Kuwait', 'Kuwait Finance House'],
    Qatar: ['Qatar National Bank', 'Qatar Islamic Bank'],
    Bahrain: ['National Bank of Bahrain', 'Ahli United Bank'],
    Oman: ['Bank Muscat', 'National Bank of Oman'],
    Morocco: ['Attijariwafa Bank', 'BMCE Bank'],
    Algeria: ['BNA', 'BEA'],
    Tunisia: ['BIAT', 'Amen Bank'],
    Libya: ['Jumhouria Bank', 'National Commercial Bank'],
    Sudan: ['Bank of Khartoum', 'Omdurman National Bank'],
    Yemen: ['CAC Bank', 'International Bank of Yemen']
  },
  transfer: {
    Syria: ['Al-Haram', 'Al-Fouad'],
    UAE: ['UAE Exchange', 'Al Ansari Exchange', 'Western Union'],
    Egypt: ['Western Union', 'MoneyGram', 'Fawry'],
    Saudi: ['Western Union', 'Al Rajhi Transfer', 'MoneyGram'],
    Turkey: ['Western Union', 'PTT', 'MoneyGram'],
    Lebanon: ['OMT', 'MoneyGram', 'Western Union'],
    Jordan: ['Western Union', 'MoneyGram', 'Ria'],
    Iraq: ['Western Union', 'MoneyGram', 'AsiaHawala'],
    Kuwait: ['Western Union', 'Al Mulla Exchange', 'MoneyGram'],
    Qatar: ['Western Union', 'Al Fardan Exchange', 'MoneyGram'],
    Bahrain: ['Western Union', 'MoneyGram', 'BFC'],
    Oman: ['Western Union', 'MoneyGram', 'Oman UAE Exchange'],
    Morocco: ['Western Union', 'MoneyGram', 'Wafacash'],
    Algeria: ['Western Union', 'MoneyGram'],
    Tunisia: ['Western Union', 'MoneyGram', 'Post Transfer'],
    Libya: ['Western Union', 'MoneyGram'],
    Sudan: ['Western Union', 'MoneyGram'],
    Yemen: ['Western Union', 'MoneyGram', 'CAC Bank Transfer']
  },
  cash: {
    Syria: ['Syriatel Cash', 'MTN Cash'],
    UAE: ['eWallet', 'NOL Pay', 'Etisalat Wallet'],
    Egypt: ['Vodafone Cash', 'Orange Cash', 'Etisalat Cash', 'WE Pay'],
    Saudi: ['STCPay', 'Urpay', 'BayanPay'],
    Turkey: ['Papara', 'Ininal', 'PayCell'],
    Lebanon: ['Touch Cash', 'Alfa Cash'],
    Jordan: ['Zain Cash', 'Orange Money', 'Umniah Mahfazti'],
    Iraq: ['Zain Cash', 'AsiaHawala', 'FastPay'],
    Kuwait: ['Zain Wallet', 'Ooredoo Wallet'],
    Qatar: ['Ooredoo Money', 'Vodafone Qatar Money'],
    Bahrain: ['Batelco Wallet', 'Benefit Pay'],
    Oman: ['eFloos', 'Omantel Pay'],
    Morocco: ['Orange Money', 'M-Wallet'],
    Algeria: ['Mobilis', 'Djezzy'],
    Tunisia: ['MobiFlouss', 'PostMobile'],
    Libya: ['Tadawul', 'Mobicash'],
    Sudan: ['MTN Money', 'Zain Cash'],
    Yemen: ['Cash Express', 'Yemen Mobile Money']
  }
};